import { Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

interface AiAnswerBadgeProps {
  model?: string;
  confidence?: number;
}

export function AiAnswerBadge({ model, confidence }: AiAnswerBadgeProps) {
  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge
            variant="outline"
            className="gap-1 bg-purple-50 text-purple-700 border-purple-200"
          >
            <Sparkles className="h-3 w-3" />
            AI Generated
          </Badge>
        </TooltipTrigger>
        <TooltipContent>
          <div className="text-sm">
            <p className="font-semibold">AI-Generated Answer</p>
            <p className="text-muted-foreground">
              This answer was generated by AI. Please verify before use.
            </p>
            {model && (
              <p className="text-xs mt-1">Model: {model}</p>
            )}
            {confidence && (
              <p className="text-xs">Confidence: {(confidence * 100).toFixed(0)}%</p>
            )}
          </div>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
