import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, Bot, ChevronDown, ChevronUp } from "lucide-react";
import { MarkdownRenderer } from "./MarkdownRenderer";

interface AiAnswerCardProps {
  answer: string;
  generatedAt: string;
  model: string;
  images?: string[];
}



export const AiAnswerCard = ({ answer, generatedAt, model, images }: AiAnswerCardProps) => {
  const [isExpanded, setIsExpanded] = useState(false);
  
  return (
    <Card className="p-4 md:p-6 bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-50 dark:from-purple-950/20 dark:via-blue-950/20 dark:to-indigo-950/20 border-2 border-purple-200 dark:border-purple-800 shadow-lg">
      <div className="flex items-start gap-3 mb-4">
        <div className="p-2 bg-gradient-to-br from-purple-600 to-blue-600 rounded-lg">
          <Bot className="h-5 w-5 text-white" />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="font-semibold text-lg">AI Generated Answer</h3>
            <Badge variant="secondary" className="gap-1 bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300">
              <Sparkles className="h-3 w-3" />
              {model}
            </Badge>
            {images && images.length > 0 && (
              <Badge variant="secondary" className="gap-1 bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300">
                📊 {images.length} diagram{images.length > 1 ? 's' : ''}
              </Badge>
            )}
          </div>
          <p className="text-xs text-muted-foreground">
            Generated {new Date(generatedAt).toLocaleString()}
          </p>
        </div>
      </div>

      {/* Display generated diagrams/images */}
      {images && images.length > 0 && (
        <div className="mb-6 space-y-4">
          <h4 className="font-semibold text-sm flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-purple-600" />
            AI-Generated Diagrams
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {images.map((image, index) => (
              <div key={index} className="rounded-lg overflow-hidden border-2 border-purple-200 dark:border-purple-700 bg-white">
                <img 
                  src={image} 
                  alt={`Diagram ${index + 1}`}
                  className="w-full h-auto"
                />
              </div>
            ))}
          </div>
        </div>
      )}

      <div 
        className="relative overflow-hidden transition-all duration-300"
        style={{ maxHeight: isExpanded ? 'none' : '400px' }}
      >
        <div 
          className="overflow-y-auto prose max-w-none"
          style={{ maxHeight: isExpanded ? 'none' : '400px' }}
        >
          <MarkdownRenderer content={answer} />
        </div>
        {!isExpanded && (
          <div className="absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-purple-50 via-purple-50/80 to-transparent dark:from-purple-950/20 dark:via-purple-950/10 pointer-events-none" />
        )}
      </div>

      {/* Expand/Collapse Button */}
      <div className="flex justify-center mt-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setIsExpanded(!isExpanded)}
          className="gap-2 text-purple-700 hover:text-purple-900 dark:text-purple-300 dark:hover:text-purple-100"
        >
          {isExpanded ? (
            <>
              <ChevronUp className="h-4 w-4" />
              Show Less
            </>
          ) : (
            <>
              <ChevronDown className="h-4 w-4" />
              Show More
            </>
          )}
        </Button>
      </div>

      <div className="mt-4 pt-4 border-t border-purple-200 dark:border-purple-800">
        <p className="text-xs text-muted-foreground italic">
          💡 This answer was generated by AI{images && images.length > 0 ? ' with visual diagrams' : ''}. Please verify the solution and adapt it to your specific use case.
        </p>
      </div>
    </Card>
  );
};
