import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, Bot } from "lucide-react";

interface AiAnswerCardProps {
  answer: string;
  generatedAt: string;
  model: string;
  images?: string[];
}

// Simple markdown-like renderer for AI answers
const renderMarkdown = (text: string) => {
  // Split by code blocks
  const parts = text.split(/(```[\s\S]*?```)/g);
  
  return parts.map((part, index) => {
    // Code block
    if (part.startsWith('```')) {
      const code = part.replace(/```(\w+)?\n?/g, '').replace(/```$/g, '');
      return (
        <pre key={index} className="bg-slate-900 text-slate-100 p-4 rounded-lg overflow-x-auto my-4">
          <code className="text-sm">{code}</code>
        </pre>
      );
    }
    
    // Regular text with markdown formatting
    return (
      <div key={index} className="space-y-3">
        {part.split('\n\n').map((paragraph, pIndex) => {
          // Headers
          if (paragraph.startsWith('## ')) {
            return <h2 key={pIndex} className="text-xl font-bold mt-6 mb-3">{paragraph.replace('## ', '')}</h2>;
          }
          if (paragraph.startsWith('### ')) {
            return <h3 key={pIndex} className="text-lg font-semibold mt-4 mb-2">{paragraph.replace('### ', '')}</h3>;
          }
          
          // Lists
          if (paragraph.includes('\n- ')) {
            const items = paragraph.split('\n').filter(line => line.startsWith('- '));
            return (
              <ul key={pIndex} className="list-disc list-inside space-y-1 ml-4">
                {items.map((item, iIndex) => (
                  <li key={iIndex}>{item.replace('- ', '')}</li>
                ))}
              </ul>
            );
          }
          
          // Inline code
          const withInlineCode = paragraph.replace(/`([^`]+)`/g, '<code class="bg-slate-200 dark:bg-slate-800 px-1.5 py-0.5 rounded text-sm">$1</code>');
          
          // Bold
          const withBold = withInlineCode.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
          
          return paragraph.trim() ? (
            <p key={pIndex} className="leading-relaxed" dangerouslySetInnerHTML={{ __html: withBold }} />
          ) : null;
        })}
      </div>
    );
  });
};

export const AiAnswerCard = ({ answer, generatedAt, model, images }: AiAnswerCardProps) => {
  return (
    <Card className="p-4 md:p-6 bg-gradient-to-br from-purple-50 via-blue-50 to-indigo-50 dark:from-purple-950/20 dark:via-blue-950/20 dark:to-indigo-950/20 border-2 border-purple-200 dark:border-purple-800 shadow-lg">
      <div className="flex items-start gap-3 mb-4">
        <div className="p-2 bg-gradient-to-br from-purple-600 to-blue-600 rounded-lg">
          <Bot className="h-5 w-5 text-white" />
        </div>
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <h3 className="font-semibold text-lg">AI Generated Answer</h3>
            <Badge variant="secondary" className="gap-1 bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300">
              <Sparkles className="h-3 w-3" />
              {model}
            </Badge>
            {images && images.length > 0 && (
              <Badge variant="secondary" className="gap-1 bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300">
                📊 {images.length} diagram{images.length > 1 ? 's' : ''}
              </Badge>
            )}
          </div>
          <p className="text-xs text-muted-foreground">
            Generated {new Date(generatedAt).toLocaleString()}
          </p>
        </div>
      </div>

      {/* Display generated diagrams/images */}
      {images && images.length > 0 && (
        <div className="mb-6 space-y-4">
          <h4 className="font-semibold text-sm flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-purple-600" />
            AI-Generated Diagrams
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {images.map((image, index) => (
              <div key={index} className="rounded-lg overflow-hidden border-2 border-purple-200 dark:border-purple-700 bg-white">
                <img 
                  src={image} 
                  alt={`Diagram ${index + 1}`}
                  className="w-full h-auto"
                />
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="prose prose-sm md:prose-base max-w-none text-sm md:text-base">
        {renderMarkdown(answer)}
      </div>

      <div className="mt-4 pt-4 border-t border-purple-200 dark:border-purple-800">
        <p className="text-xs text-muted-foreground italic">
          💡 This answer was generated by AI{images && images.length > 0 ? ' with visual diagrams' : ''}. Please verify the solution and adapt it to your specific use case.
        </p>
      </div>
    </Card>
  );
};
