import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Sparkles, FileText } from "lucide-react";
import { MarkdownRenderer } from "./MarkdownRenderer";

interface SummaryModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: string;
  generatedAt: string;
}

export const SummaryModal = ({ open, onOpenChange, summary, generatedAt }: SummaryModalProps) => {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-lg">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <div className="flex-1">
              <DialogTitle className="text-xl">AI-Generated Summary</DialogTitle>
              <DialogDescription className="text-xs">
                Generated {new Date(generatedAt).toLocaleString()}
              </DialogDescription>
            </div>
            <Badge variant="secondary" className="gap-1 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300">
              <Sparkles className="h-3 w-3" />
              AI Summary
            </Badge>
          </div>
        </DialogHeader>

        <MarkdownRenderer content={summary} />

        <div className="mt-4 pt-4 border-t">
          <p className="text-xs text-muted-foreground italic">
            💡 This summary was generated by AI to help you quickly understand the discussion.
          </p>
        </div>
      </DialogContent>
    </Dialog>
  );
};
