import { useState } from "react";
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, FileText, Volume2, VolumeX } from "lucide-react";
import { MarkdownRenderer } from "./MarkdownRenderer";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";
import { aiService } from "@/api/services/ai.service";

interface SummaryDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: string;
  generatedAt: string;
}

export const SummaryDrawer = ({ open, onOpenChange, summary, generatedAt }: SummaryDrawerProps) => {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [showUpgrade, setShowUpgrade] = useState(false);

  // Stop voice when drawer closes
  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen && isSpeaking) {
      const audioElement = document.getElementById('tts-audio-drawer') as HTMLAudioElement;
      if (audioElement) {
        audioElement.pause();
        audioElement.currentTime = 0;
      }
      setIsSpeaking(false);
    }
    onOpenChange(newOpen);
  };

  const toggleVoice = () => {
    if (isSpeaking) {
      const audioElement = document.getElementById('tts-audio-drawer') as HTMLAudioElement;
      if (audioElement) {
        audioElement.pause();
        audioElement.currentTime = 0;
      }
      setIsSpeaking(false);
    } else {
      speakText(summary);
    }
  };

  const speakText = async (text: string) => {
    // Check if text is too long
    if (text.length > 500) {
      setShowUpgrade(true);
      return;
    }

    setIsSpeaking(true);
    try {
      const audioBase64 = await aiService.textToSpeech(text);
      
      const audioElement = document.getElementById('tts-audio-drawer') as HTMLAudioElement || document.createElement('audio');
      audioElement.id = 'tts-audio-drawer';
      audioElement.src = `data:audio/mpeg;base64,${audioBase64}`;
      
      audioElement.onended = () => setIsSpeaking(false);
      audioElement.onerror = () => {
        setIsSpeaking(false);
        toast({
          title: "Voice Error",
          description: "Failed to play voice. Please try again.",
          variant: "destructive",
        });
      };

      await audioElement.play();
    } catch (error) {
      setIsSpeaking(false);
      toast({
        title: "Voice Error",
        description: "Failed to generate voice. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <>
    <Drawer open={open} onOpenChange={handleOpenChange}>
      <DrawerContent className="max-h-[90vh]">
        <DrawerHeader>
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-lg">
              <FileText className="h-4 w-4 text-white" />
            </div>
            <div className="flex-1">
              <DrawerTitle className="text-left text-base">AI-Generated Summary</DrawerTitle>
              <p className="text-[10px] text-muted-foreground">
                Generated {new Date(generatedAt).toLocaleString()}
              </p>
            </div>
            <Badge variant="secondary" className="gap-1 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300 text-[10px]">
              <Sparkles className="h-2.5 w-2.5" />
              AI Summary
            </Badge>
          </div>
        </DrawerHeader>

        <div className="px-4 pb-4 overflow-y-auto">
          <div className="prose max-w-none text-xs">
            <MarkdownRenderer content={summary} />
          </div>

          <div className="flex justify-center mt-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={toggleVoice}
              className={cn(
                "gap-2",
                isSpeaking
                  ? "text-green-600 hover:text-green-700"
                  : "text-blue-700 hover:text-blue-900 dark:text-blue-300 dark:hover:text-blue-100"
              )}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="h-4 w-4" />
                  Stop
                </>
              ) : (
                <>
                  <Volume2 className="h-4 w-4" />
                  Listen
                </>
              )}
            </Button>
          </div>

          <div className="mt-4 pt-4 border-t">
            <p className="text-[10px] text-muted-foreground italic text-center">
              💡 This summary was generated by AI to help you quickly understand the discussion.
            </p>
          </div>
        </div>
      </DrawerContent>
    </Drawer>

    {/* Upgrade Drawer */}
    <Drawer open={showUpgrade} onOpenChange={setShowUpgrade}>
      <DrawerContent>
        <DrawerHeader>
          <DrawerTitle className="text-xl font-bold text-center">🎙️ Upgrade to Premium Voice</DrawerTitle>
        </DrawerHeader>
        <div className="px-4 pb-4 space-y-4">
          <div className="text-center">
            <p className="text-muted-foreground text-sm mb-4">
              This content is too long for the free voice tier.
            </p>
            <div className="bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-950/20 dark:to-blue-950/20 p-4 rounded-lg border-2 border-purple-200 dark:border-purple-800">
              <h3 className="text-lg font-bold mb-2">Premium Voice Features</h3>
              <ul className="text-left space-y-2 text-xs">
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Unlimited voice length
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Premium voice quality
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Multiple voice options
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Faster generation
                </li>
              </ul>
              <div className="mt-4 pt-4 border-t">
                <p className="text-2xl font-bold text-purple-600">$5/month</p>
                <p className="text-xs text-muted-foreground">Cancel anytime</p>
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" className="flex-1" onClick={() => setShowUpgrade(false)}>
              Maybe Later
            </Button>
            <Button className="flex-1 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700">
              Upgrade Now
            </Button>
          </div>
        </div>
      </DrawerContent>
    </Drawer>
    </>
  );
};
