import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, FileText, Volume2, VolumeX } from "lucide-react";
import { MarkdownRenderer } from "./MarkdownRenderer";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";
import { aiService } from "@/api/services/ai.service";

interface SummaryModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: string;
  generatedAt: string;
}

export const SummaryModal = ({ open, onOpenChange, summary, generatedAt }: SummaryModalProps) => {
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [showUpgrade, setShowUpgrade] = useState(false);

  // Stop voice when modal closes
  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen && isSpeaking) {
      const audioElement = document.getElementById('tts-audio-summary') as HTMLAudioElement;
      if (audioElement) {
        audioElement.pause();
        audioElement.currentTime = 0;
      }
      setIsSpeaking(false);
    }
    onOpenChange(newOpen);
  };

  const toggleVoice = () => {
    if (isSpeaking) {
      const audioElement = document.getElementById('tts-audio-summary') as HTMLAudioElement;
      if (audioElement) {
        audioElement.pause();
        audioElement.currentTime = 0;
      }
      setIsSpeaking(false);
    } else {
      speakText(summary);
    }
  };

  const speakText = async (text: string) => {
    // Check usage count
    const usageCount = parseInt(localStorage.getItem('voice_usage_count') || '0');
    
    if (usageCount >= 1) {
      setShowUpgrade(true);
      return;
    }

    // Check if text is too long
    if (text.length > 500) {
      setShowUpgrade(true);
      return;
    }

    setIsSpeaking(true);
    try {
      const audioBase64 = await aiService.textToSpeech(text);
      
      const audioElement = document.getElementById('tts-audio-summary') as HTMLAudioElement || document.createElement('audio');
      audioElement.id = 'tts-audio-summary';
      audioElement.src = `data:audio/mpeg;base64,${audioBase64}`;
      
      audioElement.onended = () => setIsSpeaking(false);
      audioElement.onerror = () => {
        setIsSpeaking(false);
        toast({
          title: "Voice Error",
          description: "Failed to play voice. Please try again.",
          variant: "destructive",
        });
      };

      await audioElement.play();
      
      // Increment usage count
      const newCount = parseInt(localStorage.getItem('voice_usage_count') || '0') + 1;
      localStorage.setItem('voice_usage_count', newCount.toString());
    } catch (error) {
      setIsSpeaking(false);
      toast({
        title: "Voice Error",
        description: "Failed to generate voice. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <>
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2 mb-2">
            <div className="p-2 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-lg">
              <FileText className="h-5 w-5 text-white" />
            </div>
            <div className="flex-1">
              <DialogTitle className="text-xl">AI-Generated Summary</DialogTitle>
              <DialogDescription className="text-xs">
                Generated {new Date(generatedAt).toLocaleString()}
              </DialogDescription>
            </div>
            <Badge variant="secondary" className="gap-1 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300">
              <Sparkles className="h-3 w-3" />
              AI Summary
            </Badge>
          </div>
        </DialogHeader>

        <MarkdownRenderer content={summary} />

        <div className="flex justify-center mt-4">
          <Button
            variant="ghost"
            size="sm"
            onClick={toggleVoice}
            className={cn(
              "gap-2",
              isSpeaking
                ? "text-green-600 hover:text-green-700"
                : "text-blue-700 hover:text-blue-900 dark:text-blue-300 dark:hover:text-blue-100"
            )}
          >
            {isSpeaking ? (
              <>
                <VolumeX className="h-4 w-4" />
                Stop
              </>
            ) : (
              <>
                <Volume2 className="h-4 w-4" />
                Listen
              </>
            )}
          </Button>
        </div>

        <div className="mt-4 pt-4 border-t">
          <p className="text-xs text-muted-foreground italic">
            💡 This summary was generated by AI to help you quickly understand the discussion.
          </p>
        </div>
      </DialogContent>
    </Dialog>

    {/* Upgrade Modal */}
    <Dialog open={showUpgrade} onOpenChange={setShowUpgrade}>
      <DialogContent className="max-w-md">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold text-center">🎙️ Upgrade to Premium Voice</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="text-center">
            <p className="text-muted-foreground mb-4">
              This content is too long for the free voice tier.
            </p>
            <div className="bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-950/20 dark:to-blue-950/20 p-6 rounded-lg border-2 border-purple-200 dark:border-purple-800">
              <h3 className="text-xl font-bold mb-2">Premium Voice Features</h3>
              <ul className="text-left space-y-2 text-sm">
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Unlimited voice length
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Premium voice quality
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Multiple voice options
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-green-600">✓</span> Faster generation
                </li>
              </ul>
              <div className="mt-4 pt-4 border-t">
                <p className="text-2xl font-bold text-purple-600">$5/month</p>
                <p className="text-xs text-muted-foreground">Cancel anytime</p>
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" className="flex-1" onClick={() => setShowUpgrade(false)}>
              Maybe Later
            </Button>
            <Button className="flex-1 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700">
              Upgrade Now
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
    </>
  );
};
