import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { Sparkles, FileText, Volume2, VolumeX } from "lucide-react";
import { MarkdownRenderer } from "./MarkdownRenderer";
import { cn } from "@/lib/utils";
import { useSummaryVoice } from "@/hooks/useSummaryVoice";
import { UpgradeView } from "./SummaryContent";
import { useIsMobile } from "@/hooks/use-mobile";

interface SummaryDisplayProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: string;
  generatedAt: string;
}

export const SummaryDisplay = ({ open, onOpenChange, summary, generatedAt }: SummaryDisplayProps) => {
  const isMobile = useIsMobile();
  const audioId = isMobile ? 'tts-audio-drawer' : 'tts-audio-summary';
  const { isSpeaking, showUpgrade, setShowUpgrade, toggleVoice, stopVoice } = useSummaryVoice(summary, audioId);

  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen) {
      stopVoice();
    }
    onOpenChange(newOpen);
  };

  const SummaryContent = () => (
    <div className="flex flex-col">
        <div className="p-4">
            <MarkdownRenderer content={summary} />
        </div>
        <div className="flex justify-center mt-4">
          <Button
            variant="ghost"
            size="sm"
            onClick={toggleVoice}
            className={cn(
              "gap-2",
              isSpeaking
                ? "text-green-600 hover:text-green-700"
                : "text-blue-700 hover:text-blue-900 dark:text-blue-300 dark:hover:text-blue-100"
            )}
          >
            {isSpeaking ? (
              <>
                <VolumeX className="h-4 w-4" />
                Stop
              </>
            ) : (
              <>
                <Volume2 className="h-4 w-4" />
                Listen
              </>
            )}
          </Button>
        </div>

        <div className="mt-4 pt-4 border-t">
          <p className="text-xs text-muted-foreground italic text-center">
            💡 This summary was generated by AI to help you quickly understand the discussion.
          </p>
        </div>
    </div>
  );

  const header = (
    <div className="flex items-center gap-2 mb-2">
        <div className="p-2 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-lg">
            <FileText className="h-5 w-5 text-white" />
        </div>
        <div className="flex-1">
            <DialogTitle className="text-xl">AI-Generated Summary</DialogTitle>
            <DialogDescription className="text-xs">
                Generated {new Date(generatedAt).toLocaleString()}
            </DialogDescription>
        </div>
        <Badge variant="secondary" className="gap-1 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300">
            <Sparkles className="h-3 w-3" />
            AI Summary
        </Badge>
    </div>
  )


  if (isMobile) {
    return (
      <>
        <Drawer open={open} onOpenChange={handleOpenChange}>
          <DrawerContent className="max-h-[90vh]">
            <DrawerHeader>
                {header}
            </DrawerHeader>
            <div className="px-4 pb-4 overflow-y-auto">
              <SummaryContent />
            </div>
          </DrawerContent>
        </Drawer>
        <UpgradeView showUpgrade={showUpgrade} setShowUpgrade={setShowUpgrade} isMobile={isMobile} />
      </>
    );
  }

  return (
    <>
      <Dialog open={open} onOpenChange={handleOpenChange}>
        <DialogContent className="max-w-2xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            {header}
          </DialogHeader>
          <SummaryContent />
        </DialogContent>
      </Dialog>
      <UpgradeView showUpgrade={showUpgrade} setShowUpgrade={setShowUpgrade} isMobile={isMobile} />
    </>
  );
};
