import { useState } from "react";
import { Drawer, DrawerContent, DrawerHeader, DrawerTitle } from "@/components/ui/drawer";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Sparkles, FileText, Volume2, VolumeX } from "lucide-react";
import { MarkdownRenderer } from "./MarkdownRenderer";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";

interface SummaryDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: string;
  generatedAt: string;
}

export const SummaryDrawer = ({ open, onOpenChange, summary, generatedAt }: SummaryDrawerProps) => {
  const [isSpeaking, setIsSpeaking] = useState(false);

  const toggleVoice = () => {
    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      speakText(summary);
    }
  };

  const speakText = (text: string) => {
    const cleanText = cleanTextForSpeech(text);
    const utterance = new SpeechSynthesisUtterance(cleanText);
    
    const voices = window.speechSynthesis.getVoices();
    const preferredVoice = voices.find(voice => 
      voice.name.includes('Google') && voice.lang.includes('en')
    ) || voices.find(voice => 
      voice.lang.includes('en-US') || voice.lang.includes('en-GB')
    );
    
    if (preferredVoice) {
      utterance.voice = preferredVoice;
    }
    
    utterance.rate = 0.95;
    utterance.pitch = 1.0;
    utterance.volume = 1.0;

    utterance.onstart = () => setIsSpeaking(true);
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = (event) => {
      setIsSpeaking(false);
      if (event.error !== 'canceled' && event.error !== 'interrupted') {
        toast({
          title: "Voice Error",
          description: "Failed to play voice. Please try again.",
          variant: "destructive",
        });
      }
    };

    window.speechSynthesis.speak(utterance);
  };

  const cleanTextForSpeech = (text: string): string => {
    let cleaned = text;
    cleaned = cleaned.replace(/```[\s\S]*?```/g, ' code example. ');
    cleaned = cleaned.replace(/`[^`]+`/g, ' ');
    cleaned = cleaned.replace(/#{1,6}\s+/g, '');
    cleaned = cleaned.replace(/\*\*([^*]+)\*\*/g, '$1');
    cleaned = cleaned.replace(/\*([^*]+)\*/g, '$1');
    cleaned = cleaned.replace(/__([^_]+)__/g, '$1');
    cleaned = cleaned.replace(/_([^_]+)_/g, '$1');
    cleaned = cleaned.replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
    cleaned = cleaned.replace(/^[\s]*[-*+]\s+/gm, '');
    cleaned = cleaned.replace(/^[\s]*\d+\.\s+/gm, '');
    cleaned = cleaned.replace(/\s+/g, ' ').trim();
    if (cleaned.length > 1000) {
      cleaned = cleaned.substring(0, 1000) + '... and more.';
    }
    return cleaned;
  };

  return (
    <Drawer open={open} onOpenChange={onOpenChange}>
      <DrawerContent className="max-h-[90vh]">
        <DrawerHeader>
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-lg">
              <FileText className="h-4 w-4 text-white" />
            </div>
            <div className="flex-1">
              <DrawerTitle className="text-left text-base">AI-Generated Summary</DrawerTitle>
              <p className="text-[10px] text-muted-foreground">
                Generated {new Date(generatedAt).toLocaleString()}
              </p>
            </div>
            <Badge variant="secondary" className="gap-1 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300 text-[10px]">
              <Sparkles className="h-2.5 w-2.5" />
              AI Summary
            </Badge>
          </div>
        </DrawerHeader>

        <div className="px-4 pb-4 overflow-y-auto">
          <div className="prose max-w-none text-xs">
            <MarkdownRenderer content={summary} />
          </div>

          <div className="flex justify-center mt-4">
            <Button
              variant="ghost"
              size="sm"
              onClick={toggleVoice}
              className={cn(
                "gap-2",
                isSpeaking
                  ? "text-green-600 hover:text-green-700"
                  : "text-blue-700 hover:text-blue-900 dark:text-blue-300 dark:hover:text-blue-100"
              )}
            >
              {isSpeaking ? (
                <>
                  <VolumeX className="h-4 w-4" />
                  Stop
                </>
              ) : (
                <>
                  <Volume2 className="h-4 w-4" />
                  Listen
                </>
              )}
            </Button>
          </div>

          <div className="mt-4 pt-4 border-t">
            <p className="text-[10px] text-muted-foreground italic text-center">
              💡 This summary was generated by AI to help you quickly understand the discussion.
            </p>
          </div>
        </div>
      </DrawerContent>
    </Drawer>
  );
};
